### PR TITLE
Fixed your paths to relative paths

### PR DESCRIPTION
**Pull request by shero4**

### CODE REVIEW

**Comment by nitin094-hub** [comment]
Thnx for fixing these issues. I will merge this soon.
Can you tell me where did you find this project?

**Comment by nitin094-hub** [comment]
Thnx for fixing these issues.. I will merge it soon!

**Comment by shero4** [comment]
Hey Nitin,
I received your submission for frontend dev @ BugBase, couldn't view the
details so decided to fix it haha

Best
Dhruva
Co-Founder & CEO
BugBase Security Private Limited

**Comment by nitin094-hub** [comment]
Great!

**Review by nitin094-hub — APPROVED** [review]

**Pull request merged**
